### PR TITLE
Add workflow badge "Build and Deploy"

### PR DESCRIPTION
**Pull request by dr0i**
Complements Github Actions migration.

See https://github.com/hbz/lobid/issues/433.

### CODE REVIEW

**Comment by dr0i** [comment]
Not sure if this is the proper badge, because there are two workflows:
1. Build and Deploy
2. Build

While this PR covers 1 it obviously does not 2 - because this PR doesn't show up at  [1](https://github.com/metafacture/metafacture-fix/actions?query=workflow%3A%22Build+and+Deploy%22) but only at [2](https://github.com/metafacture/metafacture-fix/actions?query=workflow%3ABuild).

**Comment by dr0i** [comment]
Same question as in https://github.com/metafacture/metafacture-flux/pull/11:
> Ah, I see: `Build` builds on every push, regardless of the name of the branch.
`Build and Deploy` does run only when pushing into the master (aka `main`) branch.
We may need then two badges, right?

**Comment by dr0i** [comment]
On a second thought: it's a badge at the README and we want to reflect the status of the main/master branch there. No second badge is needed.

**Review by katauber — COMMENTED** [review]
+1

**Review by katauber — APPROVED** [review]

**Comment by dr0i** [comment]
Merged, closed.

**Pull request merged**
