### PR TITLE
255 make thread safe

### PR DESCRIPTION
**Pull request by dr0i**
Helps to prevent race conditions.

See https://github.com/metafacture/metafacture-fix/issues/255 .
See also https://github.com/metafacture/metafacture-core/pull/465 for adaptions needed in dependency `metafacture-core`.

### CODE REVIEW

**Comment by blackwinter** [comment]
General question (also applies to metafacture/metafacture-core#465): Can you expand a little on your rationale? How did you arrive at these specific synchronization points? Some of them don't make sense to me at first glance.

Also: Can you document in #255 the cause for each error you got?

**Comment by dr0i** [comment]
Sure: at first I followed the exceptions described in #255. Further Exceptions appear nonetheless, eliminating them with further `synchronized`. As theses Exceptions appear after a longer time of ETL of the basedump, I put in multiple `synchronized` to go on quicker. At one point I tried to boil down where exactly a `synchronized` would make sense, but because of the needed time to check these (unpredictable) race conditions that became to time intensive. I experienced no problem with having _too much_ of `synchronized` rather than _to little_ I decided to put them everywhere where they might make sense.
I appreciate your review and there might well be a dozen of superflous `synchronized`, you may remove them at your will.

**Comment by dr0i** [comment]
This breaks down performance significantly. More brain has to put into that, reducing the needed synchronized to a minimum. Or maybe dump the idea of fixing this at all - loss of documents seems not to be that big.

**Comment by blackwinter** [comment]
If we can find the root cause(s) we might be able to put in a targeted fix. But I agree wholeheartedly, sprinkling `synchronized` all over the place might not be the best way to go about it ;)

**Comment by dr0i** [comment]
Closed in favor of https://github.com/metafacture/metafacture-fix/pull/263.

**Pull request closed without merging**
