### PR TITLE
Add `put_macro()`/`call_macro()` Fix bind and function.

### PR DESCRIPTION
**Pull request by blackwinter**
Ports Metamorph [macros](https://github.com/metafacture/metafacture-core/wiki/Metamorph-User-Guide#defining-macros) to Metafix.

Open questions:

- Should the function be named `call_macro()` instead?
- Should calling an unknown macro throw an exception?

### CODE REVIEW

**Comment by blackwinter** [comment]
There might be an issue with local variables not being available inside binds in a macro. I'll investigate.

**Comment by fsteeg** [comment]
> Should the function be named `call_macro()` instead?

I think that's clearer. Also, how about `put_macro` for the bind, like `put_map` and `put_var`?

> Should calling an unknown macro throw an exception?

I think so, otherwise a typo in the macro name would cause it to be silently skipped, right?

**Comment by blackwinter** [comment]
Thanks for your feedback. I've applied it in 1d06fef.

**Review by fsteeg — APPROVED** [review]

**Comment by blackwinter** [comment]
> I would add in the `README.md` how to define and call the variables in the macro.

They are just passed as options and used like any other (global) variables. What would you suggest?

**Review by TobiasNx — APPROVED** [review]
One suggestion for the README.md otherwise +1 nice!

**Comment by TobiasNx** [comment]
+1

**Pull request merged**
