### PR TITLE
Add draft for new find fix paths modul #347

### LINKED ISSUE #347: Add flux-command for easily finding path for certain value
Add to the inspection commands: `list-fix-path` and `list-fix-values`
a flux command for identifying a path to a certain value would be great without hassling with triples:

```
| fix("nothing()",repeatedFieldsToEntities="true")
| flatten
| stream-to-triples
| filter-triples(objectpattern="[value]")
| template("${p}\t ${o}")
```

a macro command like `find-fix-path("[value]")` would be nice.

[See example in playground.](https://metafacture.org/playground/?flux=inputFile+//+This+is+a+variable+for+the+input+data.%0A%0A//+These+are+Flux+commands.%0A%7C+open-file%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%28%22nothing%28%29%22%2CrepeatedFieldsToEntities%3D%22true%22%29%0A%7C+flatten%0A%7C+stream-to-triples%0A%7C+filter-triples%28objectpattern%3D%22example%22%29%0A%7C+template%28%22%24%7Bp%7D\t+%24%7Bo%7D%22%29%0A%7C+print%0A%3B%0A&data=%7B%0A++++%22Hello%22%3A+%22World%22%2C%0A++++%22This%22%3A+%5B%22is%22%2C%22an%22%2C%22input%22%2C%22example%22%5D%2C%0A++++%22Please%22%3A+%22Paste+your+input+data+here%2C+if+needed%22%0A%7D)

### PR DESCRIPTION
**Pull request by TobiasNx**
See #347

@fsteeg as author of the `list-fix-paths` and `list-fix-value` wrappers could you review this new wrapper for finding the paths/keys to given value-patterns.

### CODE REVIEW

**Review by dr0i — CHANGES_REQUESTED** [review]
don't commit the compiled `class`. Always and only the source (`*.java`)

**Comment by TobiasNx** [comment]
Thanks @dr0i can you elaborate a little bit? For a noob like me? Where can I see if the class is compiled? And how can I keep the source?

**Comment by dr0i** [comment]
All java source files have the file suffix `java` while all there compiled counterparts have `class`.
You can keep the source by adding and commiting it. Its name is `FindFixPaths.java`.

**Comment by TobiasNx** [comment]
Thanks did that. I compiled that and have run the following script with:
`$ ./gradlew metafix-runner:run --args='/home/tobias/git/metafacture_workflows/find-Fix-Paths/test.flux'`

```
"https://d-nb.info/1106253078/about/marcxml"
| open-http(accept="application/xml")
| decode-xml
| handle-marcxml
| find-fix-paths(".*ETL.*")
| print
;
```

it returns empty, should return:
`24510.a	 Automating ETL processes using the domain-specific modeling approach`

https://metafacture.org/playground/?flux=%22https%3A//d-nb.info/1106253078/about/marcxml%22%0A%7C+open-http%28accept%3D%22application/xml%22%29%0A%7C+decode-xml%0A%7C+handle-marcxml%0A%7C+fix%28%22nothing%28%29%22%2CrepeatedFieldsToEntities%3D%22true%22%29%0A%7C+flatten%0A%7C+stream-to-triples%0A%7C+filter-triples%28objectpattern%3D%22.%2AETL.%2A%22%29%0A%7C+template%28%22%24%7Bp%7D\t+%24%7Bo%7D%22%29%0A%7C+print%0A%3B%0A

**Comment by TobiasNx** [comment]
> Thanks did that. I compiled that and have run the following script with: `$ ./gradlew metafix-runner:run --args='/home/tobias/git/metafacture_workflows/find-Fix-Paths/test.flux'`
> 
> ```
> "https://d-nb.info/1106253078/about/marcxml"
> | open-http(accept="application/xml")
> | decode-xml
> | handle-marcxml
> | find-fix-paths(".*ETL.*")
> | print
> ;
> ```
> 
> it returns empty, should return: `24510.a Automating ETL processes using the domain-specific modeling approach`
> 
> [https://metafacture.org/playground/?flux=%22https%3A//d-nb.info/1106253078/about/marcxml%22%0A%7C+open-http%28accept%3D%22application/xml%22%29%0A%7C+decode-xml%0A%7C+handle-marcxml%0A%7C+fix%28%22nothing%28%29%22%2CrepeatedFieldsToEntities%3D%22true%22%29%0A%7C+flatten%0A%7C+stream-to-triples%0A%7C+filter-triples%28objectpattern%3D%22.%2AETL.%2A%22%29%0A%7C+template%28%22%24%7Bp%7D\t+%24%7Bo%7D%22%29%0A%7C+print%0A%3B%0A](https://metafacture.org/playground/?flux=%22https%3A//d-nb.info/1106253078/about/marcxml%22%0A%7C+open-http%28accept%3D%22application/xml%22%29%0A%7C+decode-xml%0A%7C+handle-marcxml%0A%7C+fix%28%22nothing%28%29%22%2CrepeatedFieldsToEntities%3D%22true%22%29%0A%7C+flatten%0A%7C+stream-to-triples%0A%7C+filter-triples%28objectpattern%3D%22.%2AETL.%2A%22%29%0A%7C+template%28%22%24%7Bp%7D%5Ct+%24%7Bo%7D%22%29%0A%7C+print%0A%3B%0A)

I assume that the string for `objectPattern` is not passed through somehow and therefore the result is emtpy.

**Comment by TobiasNx** [comment]
> I assume that the string for `objectPattern` is not passed through somehow and therefore the result is emtpy.


@dr0i any idea why the string is not passed through?

**Comment by TobiasNx** [comment]
Thanks to @dr0i this now seems to work. @fsteeg could perhaps review this.

**Review by fsteeg — APPROVED** [review]
Cool!

Just two inline suggestions (your name).

**Review by dr0i — APPROVED** [review]

**Pull request merged**
