### PR TITLE
Don't restrict bind scope to the bound var

### LINKED ISSUE #66: Make the full record available in binds
See https://github.com/metafacture/metafacture-fix/pull/60#pullrequestreview-795591354.

Functional review: @TobiasNx
Code review: @blackwinter

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #66

### CODE REVIEW

**Comment by blackwinter** [comment]
I'm in the process of introducing _virtual_ (internal) fields (for `_id`, see #63). Those could be leveraged here as well (add `var` as virtual field). I'll hold off with my PR until this one is merged.

**Comment by blackwinter** [comment]
Catmandu only does this when the `var` option is given ([ref.](https://github.com/metafacture/metafacture-fix/issues/66#issuecomment-963272919)). OTOH, there's no test for a `list` bind without `var` right now.

Options:

1. Treat `list` bind without `var` as _undefined behaviour_ - subject to change (without notice).
2. Add support for both cases (including tests).
3. Disallow `list` bind without `var` for the time being (including tests).
4. Officially support current behaviour (including tests) - intentionally diverging from Catmandu.

My preference would be 2.

**Comment by fsteeg** [comment]
> Catmandu only does this when the var option is given

I don't get that. What's the point in not making the record available, *in particular* if we bind nothing to a var? Could that be a bug in Catmandu?

In general, I'd like to focus on getting our use cases working, and not worry too much about Catmandu compatibility at this point, therefore I'd vote for 1:

> Treat list bind without var as undefined behaviour - subject to change (without notice)

**Comment by blackwinter** [comment]
> What's the point in not making the record available,

That was the initial implementation, so there must have been _some_ point to it ;)

> in particular if we bind nothing to a var?

Then your scope is determined by the path, you just can't access the whole record. If you need that, bind to a variable.

> Could that be a bug in Catmandu?

As I said, I don't know if it's documented anywhere. But it was introduced as a feature enhancement (LibreCat/Catmandu@88dd6d1), the restricted scope was the original behaviour, AFAICS.

**Review by blackwinter — APPROVED** [review]

**Comment by fsteeg** [comment]
Oh, that was fast. Here's what I wrote but waited to send after the build was fixed:

I've added access to the bound values to understand Catmandu's behavior in https://github.com/hbz/Catmandu/commit/093c6cb and added corresponding tests and implementation in https://github.com/metafacture/metafacture-fix/pull/83/commits/1b1ee8e.

I'll commit further tweaks based on your comments.

**Comment by fsteeg** [comment]
Thanks for the quick review, I think your points should be addressed in https://github.com/metafacture/metafacture-fix/pull/83/commits/a70a7b886d97e5f6177a8cc3790ebd5c32664664.

I will merge once all conversations are resolved.

**Comment by blackwinter** [comment]
Great, thanks! I think everything's resolved now.

**Pull request merged**
