### PR TITLE
102-integrationTestsForNewPath

### PR DESCRIPTION
**Pull request by TobiasNx**
I collect integration test for changes that I found.

### CODE REVIEW

**Comment by TobiasNx** [comment]
These are the OERSI derived integration tests of problems that fail. I don't know how to proceed here.

**Comment by blackwinter** [comment]
Some preliminary remarks:

1. Failing tests should be marked as "to do".
2. Why is @katauber a reviewer and not @fsteeg?
3. This pull request should probably be marked as "Ready for review".

**Comment by fsteeg** [comment]
> The failing tests without "todo" work with the master.

Hm, I have merged `102-integrationTestsForNewPath` locally into `master` and I get:

`FAILURE: 137 passed, 8 failed, 69 skipped, 0 invalid`

**Comment by TobiasNx** [comment]
> > The failing tests without "todo" work with the master.
> 
> Hm, I have merged `102-integrationTestsForNewPath` locally into `master` and I get:
> 
> `FAILURE: 137 passed, 8 failed, 69 skipped, 0 invalid`

This is upbranched from `102-path` to test therefore you merged all commits from `102-path` too.

**Comment by fsteeg** [comment]
> This is upbranched from 102-path to test therefore you merged all commits from 102-path too.

I see, how did you verify this statement then:

> The failing tests without "todo" work with the master.

Could you push that somewhere?

The PR should contain just the new integration tests, so I can test them both with master and 102-path.

**Comment by TobiasNx** [comment]
To compare I moved my commits to a new PR for MAster #203

**Comment by TobiasNx** [comment]
I close these so that we can use them from master.

**Pull request closed without merging**
