### PR TITLE
Add integration test replace_all (#251)

### PR DESCRIPTION
**Pull request by dr0i**
See #251.

### CODE REVIEW

**Comment by dr0i** [comment]
See `method/fromXml/toJson/replace_toUpper: ERROR` :
> Exception in thread "main" org.metafacture.metafix.FixProcessException: Error while executing Fix expression (at file:/home/pc/git/metafacture-fix/metafix/src/test/resources/org/metafacture/metafix/integration/method/fromXml/toJson/replace_toUpper/test.fix, line 25): replace_all("contribution[].*.agent.label","(?<!\\p{Upper})\\.$|[,]$","")
at org.metafacture.metafix.RecordTransformer.tryRun(RecordTransformer.java:247)
[...]
at org.metafacture.runner.Flux.main(Flux.java:85)
Caused by: java.lang.IllegalArgumentException: Can't find: 2 in: null
at org.metafacture.metafix.FixPath.insertInto(FixPath.java:297)
[...]

**Review by blackwinter — APPROVED** [review]

**Comment by blackwinter** [comment]
Thanks! Seems to be related to `label` being an array.

**Comment by dr0i** [comment]
@TobiasNx you can try to use this to improve our transformation script already.

**Comment by dr0i** [comment]
@TobiasNx the id of the xml is '99370763882706441'.

**Comment by TobiasNx** [comment]
This is releated to https://github.com/hbz/lobid-resources/issues/1372

**Pull request merged**
