### PR TITLE
Switch to next dev version, add instructions on releasing

### LINKED ISSUE #286: Release 0.4.0 on GitHub
If there are no objections, I'd like to like to release the current master as 0.4.0 on GitHub:

- [x] Bump development version to 0.5.0-SNAPSHOT
- [x] Create 0.4.0 GitHub packages
- [x] Create 0.4.0 GitHub release with distribution download

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #286.

### CODE REVIEW

**Review by blackwinter — APPROVED** [review]
On top of contributor and user documentation, we're now adding maintainer documentation to the mix. But it's of limited value to anyone else, so I think it might be better placed at the end.

Otherwise :+1:

**Comment by fsteeg** [comment]
> That's also a possibility, yes. Or creating a wiki page (like you're already doing for [metafacture-core](https://github.com/metafacture/metafacture-core/wiki/Maintainer-Guidelines) and [lobid-resources](https://github.com/hbz/lobid-resources/wiki/Maintainer-Guidelines)). I don't have a fully formed opinion either way yet.

In other repos, we generally try to avoid the wiki to have all information inside the actual git repo.

**Comment by blackwinter** [comment]
> In other repos, we generally try to avoid the wiki to have all information inside the actual git repo.

As I said, I'm on the fence myself. If there's precedent for `MAINTAINING.md`, I have no objections.

**Comment by fsteeg** [comment]
>  If there's precedent for `MAINTAINING.md`, I have no objections.

You mean in our repos? No, this would be the first one. But I think it makes sense and is consistent with the existing `CONTRIBUTING.md`. It seems to be [used by others](https://github.com/search?q=%22maintaining.md%22&type=code) too.

**Comment by blackwinter** [comment]
> You mean in our repos?

I was referring to:

> In other repos, we generally try to avoid the wiki to have all information inside the actual git repo.

But it's fine, go ahead.

**Pull request merged**
