### PR TITLE
Add integration test for #226

### PR DESCRIPTION
**Pull request by TobiasNx**
Add integration test for #226

### CODE REVIEW

**Review by blackwinter — COMMENTED** [review]
You marked both integration tests as "todo". But is there even consent yet that #226 is actually a bug?

**Comment by TobiasNx** [comment]
No there is no explicit consent yet. But `paste` outputs even an empty field if there is no element that is matching the function. I think this behaviour is not right.

**Comment by blackwinter** [comment]
Okay, let's reach an agreement on the issue first, shall we? Then we can decide what to do about it.

**Comment by TobiasNx** [comment]
I am closing this PR, since metafix `paste` has the same behaviour as catmandu `paste`

**Pull request closed without merging**
