### PR TITLE
WIP: track changes for oersi-etl

### PR DESCRIPTION
**Pull request by fsteeg**
This is a WIP-PR to track the changes in metafacture-fix used in oersi-etl: https://gitlab.com/oersi/oersi-etl

Sample using these Fix features: https://gitlab.com/oersi/oersi-etl/-/blob/develop/data/to-oersibackend/oernds-to-oersi.flux

For merging these, it might make sense to cherry-pick into new, individual PRs for specific issues (like https://github.com/metafacture/metafacture-fix/issues/5).

### CODE REVIEW

**Comment by blackwinter** [comment]
Can the first commit (683c247) be merged? Either before #60 is merged or right after. I think it would be valuable to have a stable identifier going forward.

**Comment by fsteeg** [comment]
> Can the first commit ([683c247](https://github.com/metafacture/metafacture-fix/commit/683c247dfbeb213d4a6ecb9b4829071e6b422907)) be merged? Either before #60 is merged or right after. I think it would be valuable to have a stable identifier going forward.

Right, thanks, good catch, that was the plan, but I forgot. Added to 35-metafix in https://github.com/metafacture/metafacture-fix/pull/60/commits/1fe336bf81f8c490d20f2ffd7bfa53ad93063486.

**Comment by blackwinter** [comment]
BTW (in the context of 683c247): Is there a reason why we don't just rename the subproject directories, mimicking the layout in metafacture-core?

- `org.metafacture.fix/` -> `metafix/` (no need to override the project name anymore)
- `org.metafacture.fix.ide/` -> `metafix-ide/`
- `org.metafacture.fix.vsc/` -> `metafix-vsc/`
- `org.metafacture.fix.web/` -> `metafix-web/`

**Comment by fsteeg** [comment]
> BTW (in the context of [683c247](https://github.com/metafacture/metafacture-fix/commit/683c247dfbeb213d4a6ecb9b4829071e6b422907)): Is there a reason why we don't just rename the subproject directories, mimicking the layout in metafacture-core?

Sounds good. The current naming is the Xtext/Eclipse convention, but it should work to set up MWE workflow etc. for the simpler directories/names.

**Pull request closed without merging**
