### PR TITLE
Metafacture core 415 add skos lookup

### PR DESCRIPTION
**Pull request by dr0i**
This PR builds on https://github.com/metafacture/metafacture-fix/pull/229 with  the master rebased and some more improvements following https://github.com/metafacture/metafacture-fix/pull/229/files#r977759388 .

See [metafacture-core#415 .](https://github.com/metafacture/metafacture-core/issues/415).

### CODE REVIEW

**Comment by blackwinter** [comment]
I find it a little unfortunate that the (extensive) discussion gets bifurcated here. Is there a specific reason not to force-push into the original branch?

**Comment by dr0i** [comment]
>  Is there a specific reason not to force-push into the original branch?

I am not sure, but would this not change the the commits, the code and hence make the discussion/comments disrupted? If this is not so I would indeed like to force-push into the original branch as you suggest.

**Comment by blackwinter** [comment]
> I am not sure, but would this not change the the commits, the code and hence make the discussion/comments disrupted?

Yes, it would. But the commits and comments are still reachable and the original context is still shown. And you already did force-push into that branch multiple times ;)

**Comment by dr0i** [comment]
Ok, I am gonna do this - thx for the explanation.

**Comment by dr0i** [comment]
Hm, but now indeed one of your very valuable review-inline-code-comment seems to be gone in https://github.com/metafacture/metafacture-fix/pull/229/files ... or I can just not find it?

**Comment by blackwinter** [comment]
The comments are in the "discussion" tab. Which one are you talking about?

**Comment by dr0i** [comment]
If I try to open one of the outdated conversations I get "We went looking everywhere, but couldn’t find those commits." . It was a longer comment where you were musing i.a. about incorporating `lookup_rdf `into `lookup`.

**Comment by blackwinter** [comment]
> If I try to open one of the outdated conversations I get "We went looking everywhere, but couldn’t find those commits." .

That does indeed sound bad. Which one was it?

> It was a longer comment where you were musing i.a. about incorporating `lookup_rdf `into `lookup`.

Are you possibly talking about [this one](https://github.com/metafacture/metafacture-fix/pull/229#discussion_r979205154)?

**Comment by dr0i** [comment]
> Are you possibly talking about https://github.com/metafacture/metafacture-fix/pull/229#discussion_r979205154?

Wasn't _exactly_ this one, but yes, that the core idea. Also https://github.com/metafacture/metafacture-fix/pull/229#discussion_r997176787 . If I am not mistaken those PR comments were also in the "inline-code", a bit different, but that's better than nothing.

**Comment by dr0i** [comment]
Lessons learned:
- don't force push (don't rebase master - merge instead), as noted in the [CONTRIBUTING.md](https://github.com/metafacture/metafacture-core/blob/master/CONTRIBUTING.md)

**Comment by blackwinter** [comment]
How is that the lesson learned? I don't get it...

**Comment by dr0i** [comment]
I rebased to get the master into https://github.com/metafacture/metafacture-fix/pull/229 . If I would not have rebased, but ` git pull --no-ff origin` there would be no forece-pushing. That's my "lesson learned", or better "reminder".

**Comment by blackwinter** [comment]
Yeah, well, I've always been in favour of rebase instead of merge and that's why I argued for it. But if you think that merge works better for you then stick to it.

**Pull request closed without merging**
